name: Run Daily Fetch Cursors

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch-latest-cursors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Run fetch_latest_cursors.js
      run: |
        node fetch_latest_cursors.js
